// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/lark_service.proto

package go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppImageTagUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 更改的容器名称
	ContainerName string `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// git commit 内容
	CommitMessage string `protobuf:"bytes,2,opt,name=commit_message,json=commitMessage,proto3" json:"commit_message,omitempty"`
	// 作者
	Author string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	// 新的镜像
	Image string `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *AppImageTagUpdateRequest) Reset() {
	*x = AppImageTagUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lark_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppImageTagUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppImageTagUpdateRequest) ProtoMessage() {}

func (x *AppImageTagUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lark_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppImageTagUpdateRequest.ProtoReflect.Descriptor instead.
func (*AppImageTagUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_lark_service_proto_rawDescGZIP(), []int{0}
}

func (x *AppImageTagUpdateRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *AppImageTagUpdateRequest) GetCommitMessage() string {
	if x != nil {
		return x.CommitMessage
	}
	return ""
}

func (x *AppImageTagUpdateRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *AppImageTagUpdateRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type AppImageTagUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AppImageTagUpdateResponse) Reset() {
	*x = AppImageTagUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lark_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppImageTagUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppImageTagUpdateResponse) ProtoMessage() {}

func (x *AppImageTagUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lark_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppImageTagUpdateResponse.ProtoReflect.Descriptor instead.
func (*AppImageTagUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_lark_service_proto_rawDescGZIP(), []int{1}
}

type ImagesSyncDoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 镜像名称
	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *ImagesSyncDoneRequest) Reset() {
	*x = ImagesSyncDoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lark_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesSyncDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesSyncDoneRequest) ProtoMessage() {}

func (x *ImagesSyncDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lark_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesSyncDoneRequest.ProtoReflect.Descriptor instead.
func (*ImagesSyncDoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_lark_service_proto_rawDescGZIP(), []int{2}
}

func (x *ImagesSyncDoneRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type ImagesSyncDoneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImagesSyncDoneResponse) Reset() {
	*x = ImagesSyncDoneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lark_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesSyncDoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesSyncDoneResponse) ProtoMessage() {}

func (x *ImagesSyncDoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lark_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesSyncDoneResponse.ProtoReflect.Descriptor instead.
func (*ImagesSyncDoneResponse) Descriptor() ([]byte, []int) {
	return file_proto_lark_service_proto_rawDescGZIP(), []int{3}
}

var File_proto_lark_service_proto protoreflect.FileDescriptor

var file_proto_lark_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x72, 0x6b, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6c, 0x61, 0x72, 0x6b,
	0x22, 0x96, 0x01, 0x0a, 0x18, 0x41, 0x70, 0x70, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x41, 0x70, 0x70,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x15, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x53, 0x79, 0x6e, 0x63, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x53,
	0x79, 0x6e, 0x63, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0xb0, 0x01, 0x0a, 0x0b, 0x4c, 0x61, 0x72, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x54, 0x0a, 0x11, 0x41, 0x70, 0x70, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x6c, 0x61, 0x72, 0x6b, 0x2e, 0x41, 0x70, 0x70, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6c, 0x61, 0x72, 0x6b, 0x2e, 0x41, 0x70, 0x70, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x53,
	0x79, 0x6e, 0x63, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x1b, 0x2e, 0x6c, 0x61, 0x72, 0x6b, 0x2e, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6c, 0x61, 0x72, 0x6b, 0x2e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_lark_service_proto_rawDescOnce sync.Once
	file_proto_lark_service_proto_rawDescData = file_proto_lark_service_proto_rawDesc
)

func file_proto_lark_service_proto_rawDescGZIP() []byte {
	file_proto_lark_service_proto_rawDescOnce.Do(func() {
		file_proto_lark_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lark_service_proto_rawDescData)
	})
	return file_proto_lark_service_proto_rawDescData
}

var file_proto_lark_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_lark_service_proto_goTypes = []interface{}{
	(*AppImageTagUpdateRequest)(nil),  // 0: lark.AppImageTagUpdateRequest
	(*AppImageTagUpdateResponse)(nil), // 1: lark.AppImageTagUpdateResponse
	(*ImagesSyncDoneRequest)(nil),     // 2: lark.ImagesSyncDoneRequest
	(*ImagesSyncDoneResponse)(nil),    // 3: lark.ImagesSyncDoneResponse
}
var file_proto_lark_service_proto_depIdxs = []int32{
	0, // 0: lark.LarkService.AppImageTagUpdate:input_type -> lark.AppImageTagUpdateRequest
	2, // 1: lark.LarkService.ImagesSyncDone:input_type -> lark.ImagesSyncDoneRequest
	1, // 2: lark.LarkService.AppImageTagUpdate:output_type -> lark.AppImageTagUpdateResponse
	3, // 3: lark.LarkService.ImagesSyncDone:output_type -> lark.ImagesSyncDoneResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_lark_service_proto_init() }
func file_proto_lark_service_proto_init() {
	if File_proto_lark_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lark_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppImageTagUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lark_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppImageTagUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lark_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesSyncDoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lark_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesSyncDoneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lark_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lark_service_proto_goTypes,
		DependencyIndexes: file_proto_lark_service_proto_depIdxs,
		MessageInfos:      file_proto_lark_service_proto_msgTypes,
	}.Build()
	File_proto_lark_service_proto = out.File
	file_proto_lark_service_proto_rawDesc = nil
	file_proto_lark_service_proto_goTypes = nil
	file_proto_lark_service_proto_depIdxs = nil
}
